function [err, labels] = compareStorageFiles2(file1, file2)
% Utility to compare two storage files that are supposed to contain the
% same data, with perhaps different column orders or a major subset of
% columns.
% This version of compareStorageFiles also allows storage files to have
% different numbers of rows, and interpolates values based on the time
% columns to compare, say, storage files generated by different dynamics
% engines or integrators, which could change the exact steps taken by the
% integrators.
% USAGE: [error, col_labels] = compareStorageFiles(file1, file2)
%
% Ajay Seth, Chand T. John
% Stanford University

S1 = read_motionFile(file1);
S2 = read_motionFile(file2);

nc1 = length(S1.labels);
nc2 = length(S2.labels);

% Get the time columns, which we assume is the first column of each file
T1 = S1.data(:,1);
T2 = S2.data(:,1);

k = 0;
for I = 1:nc1,
    col = strmatch(S1.labels{I}, S2.labels);
    if ~isempty(col),
        % If multiple indices with the same label get column closest I
        [val, ind] = min(abs(col-I));
        k = k+1;
        % Get the corresponding data columns
        Q1 = S1.data(:,I);
        Q2 = S2.data(:,col(ind));
        % Interpolate Q2 to have T1 as its new time column
        Q2 = interp1(T2,Q2,T1);
        err(:,k) = Q2-Q1;
        labels{k} = S1.labels{I};
    end
end
