function [] = format_gcdPlotTemplate(plotIndex)
% Purpose:  Formats the current subplot, identified by plotIndex, of the
%           template figure window created by create_gcdFigTemplate() 
%           or by create_jntAngMomFigTemplate().
%
% Inputs:   plotIndex is the index number of the current subplot
% ASA, 6-05

% Specify attributes of all subplots.
tFontName = 'helvetica';            % attributes of subplot titles
tFontSize = 9;
tVerticalAlignment = 'middle';
aFontName = 'helvetica';            % attributes of axis labels and ticks
aFontSize = 8;
aTickDir = 'out';
xmin = 0;                           % x-axis limits and tick labels
xmax = 100;
xval = [0 20 40 60 80 100];

% Format subplot(nPlotRows, nPlotCols, plotIndex)
switch plotIndex
    case 1
        title('pelvic obliquity (up/down)');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        ylabel('joint angle (deg)');
            a = get(gca, 'ylabel');
            set(a, 'FontName', aFontName, 'FontSize', aFontSize);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-25 25], 'ytick', [-20:20:20], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');

    case 2
        title('pelvic tilt (ant/post)');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-15 35], 'ytick', [-10:20:30], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
   
     case 3
        title('pelvic rotation (int/ext)');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-40 40], 'ytick', [-30:20:30], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
     case 4
        title('hip ad/abduction');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        ylabel('joint angle (deg)');
            a = get(gca, 'ylabel');
            set(a, 'FontName', aFontName, 'FontSize', aFontSize);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-25 25], 'ytick', [-20:20:20], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
     case 5
        title('hip flexion/extension');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-25 75], 'ytick', [-15:30:75], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
     case 6
        title('hip rotation (int/ext)');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-40 40], 'ytick', [-30:20:30], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
     case 7
        title('knee varus/valgus');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        ylabel('joint angle (deg)');
            a = get(gca, 'ylabel');
            set(a, 'FontName', aFontName, 'FontSize', aFontSize);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-25 25], 'ytick', [-20:20:20], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
     case 8
        title('knee flexion/extension');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-15 85], 'ytick', [-15:30:75], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
     case 9
        title('knee rotation (int/ext)');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-40 40], 'ytick', [-30:20:30], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
     case 10
        axis off;  

    case 11
        title('ankle dorsi/plantarflexion');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        ylabel('joint angle (deg)');
            a = get(gca, 'ylabel');
            set(a, 'FontName', aFontName, 'FontSize', aFontSize);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-40 35], 'ytick', [-30:20:30], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
     case 12
        title('foot progression (int/ext)');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-50 50], 'ytick', [-40:40:40], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
     case 13
        title('hip moment (ext/flex)');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        xlabel('% gait cycle');
            a = get(gca, 'xlabel');
            set(a, 'FontName', aFontName, 'FontSize', aFontSize);
        ylabel('joint moment (Nm/kg)');
            a = get(gca, 'ylabel');
            set(a, 'FontName', aFontName, 'FontSize', aFontSize);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-1.5 2], 'ytick', [-1:1:2], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
     case 14
        title('knee moment (ext/flex)');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        xlabel('% gait cycle');
            a = get(gca, 'xlabel');
            set(a, 'FontName', aFontName, 'FontSize', aFontSize);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-1.5 2], 'ytick', [-1:1:2], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
     case 15
        title('ankle moment (ext/flex)');
            t = get(gca, 'title');
            set(t, 'FontName', tFontName, 'FontSize', tFontSize, ...
                'VerticalAlignment', tVerticalAlignment);
        xlabel('% gait cycle');
            a = get(gca, 'xlabel');
            set(a, 'FontName', aFontName, 'FontSize', aFontSize);
        set(gca, 'xlim', [xmin xmax], 'xtick', xval, ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'ylim', [-1.5 2], 'ytick', [-1:1:2], ...
            'FontName', aFontName, 'FontSize', aFontSize, ...
            'TickDir', aTickDir);
        set(gca, 'Box', 'off');
        
end
