function ref = ref_dataFormatGillette()
% Based on ref_c3dAnalogLabels, ref_c3dVideoLabels

ref.c3dAnalogLabels.grf = {'1FX', '1FY', '1FZ', '1MX', '1MY', '1MZ', ...
                           '2FX', '2FY', '2FZ', '2MX', '2MY', '2MZ', ...
                           '3FX', '3FY', '3FZ', '3MX', '3MY', '3MZ', ...
                           '4FX', '4FY', '4FZ', '4MX', '4MY', '4MZ', ...
                           '1Fx', '1Fy', '1Fz', '1Mx', '1My', '1Mz', ...
                           '2Fx', '2Fy', '2Fz', '2Mx', '2My', '2Mz', ...
                           '3Fx', '3Fy', '3Fz', '3Mx', '3My', '3Mz', ...
                           '4Fx', '4Fy', '4Fz', '4Mx', '4My', '4Mz'};

ref.c3dAnalogLabels.groundForcePattern = {'%dFX', '%dFY', '%dFZ'};

ref.c3dAnalogLabels.emg = {'EM01', 'EM02', 'EM03', 'EM04', 'EM05', ...
                           'EM06', 'EM07', 'EM08', 'EM09', 'EM10', ...
                           'LF', 'RF', 'LM', 'RM', 'LH', 'RH',     ...
                           'LA', 'RA', 'LG', 'RG'};

ref.c3dVideoLabels.markers = ...
   {'N', 'RAC', 'LAC',                        ...  % C7, subclavicular
    'STRN', 'XYPH', 'RW', 'LW',               ...  % sternum, xyphoid
    'RASI', 'LASI', 'R', 'B',                 ...  % ASIS
    'RPSI', 'LPSI', 'PEL1', 'H',              ...  % PSIS, sacrum
    'RTHI', 'LTHI', 'RF', 'LF',               ...  % thigh
    'RUL1', 'LUL1', 'RUL2', 'LUL2',           ...  % thigh
    'RKAX', 'RKD1', 'RKD2', 'RH', 'RK', 'RP', ...  % R KAD
    'LKAX', 'LKD1', 'LKD2', 'LH', 'LK', 'LP', ...  % L KAD
    'RKNE', 'LKNE', 'RK', 'LK',               ...  % lateral knee axis
    'RMFC', 'LMFC',                           ...  % medial femoral condyle
    'RTIB', 'LTIB', 'RB', 'LB',               ...  % tibia
    'RLL1', 'LLL1',                           ...  % tibia
    'RANK', 'LANK', 'RA', 'LA',               ...  % lateral malleolus
    'RMM',  'LMM',  'RMMv', 'LMMv',           ...  % medial malleolus
    'RTOE', 'LTOE', 'RT', 'LT',               ...  % toe
    'RHEE', 'LHEE', 'RQ', 'LQ'};                   % heel
        % RASIv, LASIv, RANKv, LANKv could be added, if desired.


ref.c3dVideoLabels.jntcenters.L = {'LFEP', ...       % L HJC from Vicon PIG model
                                   'LFEO', ...       % L KJC from Vicon PIG model
                                   'LTIO', ...       % L AJC from Vicon PIG model
                                   'HIPL', ...       % L HJC from dynamic trial
                                   'KNEL'};          % L KJC from dynamic trial

ref.c3dVideoLabels.jntcenters.R = {'RFEP', ...       % R HJC from Vicon PIG model
                                   'RFEO', ...       % R KJC from Vicon PIG model
                                   'RTIO', ...       % R AJC from Vicon PIG model
                                   'HIPR', ...       % R HJC from dynamic trial
                                   'KNER'};          % R KJC from dynamic trial


ref.c3dVideoLabels.jntangles.L = {'LPelvisAngles',       ...
                                  'LHipAngles',          ...
                                  'LKneeAngles',         ...
                                  'LAnkleAngles',        ...
                                  'LFootProgressAngles', ...
                                  'LPelvisAnglesDJC',    ...
                                  'LHipAnglesDJC',       ...
                                  'LKneeAnglesDJC',      ...
                                  'LPeluisAnglesDJC'};
                                   % joint angles from Vicon PIG model;
                                   % DJC angles computed from dynamic joint centers
                                   % LPeluisAnglesDJC added to compensate for 
                                   %    typo in C3D files for 900045

ref.c3dVideoLabels.jntangles.R = {'RPelvisAngles',       ...       
                                  'RHipAngles',          ...
                                  'RKneeAngles',         ...
                                  'RAnkleAngles',        ...
                                  'RFootProgressAngles', ...
                                  'RPelvisAnglesDJC',    ...
                                  'RHipAnglesDJC',       ...
                                  'RKneeAnglesDJC'};


ref.c3dVideoLabels.jntmoments.L = {'LHipMoment', 'LKneeMoment', 'LAnkleMoment'};
ref.c3dVideoLabels.jntmoments.R = {'RHipMoment', 'RKneeMoment', 'RAnkleMoment'};


ref.c3dVideoLabels.jntpowers.L = {'LHipPower', 'LKneePower', 'LAnklePower'};
ref.c3dVideoLabels.jntpowers.R = {'RHipPower', 'RKneePower', 'RAnklePower'};

ref.emgChannels = { ...
        { 'L', 'Rectus Femoris' },      ...
        { 'R', 'Rectus Femoris' },      ...
        { 'L', 'Medial Hamstrings' },   ...
        { 'R', 'Medial Hamstrings' },   ...
        { 'L', 'Lateral Hamstrings' },  ...
        { 'R', 'Lateral Hamstrings' },  ...
        { 'L', 'Tibialis Anterior' },   ...
        { 'R', 'Tibialis Anterior' },   ...
        { 'L', 'Gastroc-Soleus' },      ...
        { 'R', 'Gastroc-Soleus' } };

ref.emgMuscleToColumnPrefix = { ...
        { 'Rectus Femoris' , 'rect_fem'},      ...
        { 'Medial Hamstrings', 'med_hams' },   ...
        { 'Lateral Hamstrings', 'lat_hams' },  ...
        { 'Tibialis Anterior', 'tib_ant' },   ...
        { 'Gastroc-Soleus', 'gas_sol' } };
		

% Specify muscles corresponding to EMG reference data of interest
% for overlaying EMG on/off times reported by Perry (1992).
% NOTE:  the muscle abbreviations must correspond to those in 
%        get_emgTimingFromPerry().
ref.muscRefList{1}  = {'RF', 'VASmed', 'VASint', 'VASlat'};
ref.muscRefList{2}  = {'RF', 'VASmed', 'VASint', 'VASlat'};
ref.muscRefList{3}  = {'SM', 'ST', 'GR', 'ADM'};
ref.muscRefList{4}  = {'SM', 'ST', 'GR', 'ADM'};
ref.muscRefList{5}  = {'BFLH', 'BFSH', 'VASlat'};
ref.muscRefList{6}  = {'BFLH', 'BFSH', 'VASlat'};
ref.muscRefList{7}  = {'TA', 'EDL', 'PERlong'};
ref.muscRefList{8}  = {'TA', 'EDL', 'PERlong'};
ref.muscRefList{9}  = {'GAS', 'SOL'};
ref.muscRefList{10} = {'GAS', 'SOL'};

ref.emgChannelsOfInterest = 1:length(ref.emgChannels);

ref.analogRate = 1080;

ref.tZeroAtFirstIC = 1;

ref.muscleActPlotLabels = @ref_muscleActPlotLabelsGillette;

return;
