#ifndef OPENSIM_SCALE_TOOL_H_ 
#define OPENSIM_SCALE_TOOL_H_
/* -------------------------------------------------------------------------- *
 *                           OpenSim:  ScaleTool.h                            *
 * -------------------------------------------------------------------------- *
 * The OpenSim API is a toolkit for musculoskeletal modeling and simulation.  *
 * See http://opensim.stanford.edu and the NOTICE file for more information.  *
 * OpenSim is developed at Stanford University and supported by the US        *
 * National Institutes of Health (U54 GM072970, R24 HD065690) and by DARPA    *
 * through the Warrior Web program.                                           *
 *                                                                            *
 * Copyright (c) 2005-2017 Stanford University and the Authors                *
 * Author(s): Peter Loan                                                      *
 *                                                                            *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may    *
 * not use this file except in compliance with the License. You may obtain a  *
 * copy of the License at http://www.apache.org/licenses/LICENSE-2.0.         *
 *                                                                            *
 * Unless required by applicable law or agreed to in writing, software        *
 * distributed under the License is distributed on an "AS IS" BASIS,          *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
 * See the License for the specific language governing permissions and        *
 * limitations under the License.                                             *
 * -------------------------------------------------------------------------- */


// INCLUDE
#include "OpenSim/Common/Object.h"
#include "OpenSim/Common/Property.h"
#include "OpenSim/Tools/GenericModelMaker.h"
#include "OpenSim/Tools/MarkerPlacer.h"
#include "OpenSim/Tools/ModelScaler.h"
#include "osimToolsDLL.h"

#include <memory>
#include <string>
namespace OpenSim {

class Model;

//=============================================================================
//=============================================================================
/**
 * A class implementing a set of parameters describing how to scale a model
 * to fit a subject, place markers on it, and do IK on one or more motion
 * trials.
 *
 * @author Peter Loan
 * @version 1.0
 */
class OSIMTOOLS_API ScaleTool : public Object {
OpenSim_DECLARE_CONCRETE_OBJECT(ScaleTool, Object);

//=============================================================================
// DATA
//=============================================================================
public:
OpenSim_DECLARE_PROPERTY(mass, double,
        "Mass of the subject in kg.  Subject-specific model generated by "
        "scaling step will have this total mass.");
OpenSim_DECLARE_PROPERTY(height, double,
        "Height of the subject in mm.  For informational "
        "purposes only (not used by scaling).");
OpenSim_DECLARE_PROPERTY(age, double,
        "Age of the subject in years.  For informational "
        "purposes only (not used by scaling).");
OpenSim_DECLARE_PROPERTY(notes, std::string, "Notes for the subject.");
OpenSim_DECLARE_PROPERTY(generic_model_maker, GenericModelMaker,
        "Specifies the name of the unscaled "
        "model (.osim) and the marker set.");
OpenSim_DECLARE_PROPERTY(model_scaler, ModelScaler,
        "Specifies parameters for scaling the model.");
OpenSim_DECLARE_PROPERTY(marker_placer, MarkerPlacer,
        "Specifies parameters for placing markers on "
        "the model once a model is scaled. ");
OpenSim_DECLARE_PROPERTY(path_to_subject, std::string,
        "All files in workflow are specified relative to"
        "where the subject file is. "
        "Need to keep track of that in case absolute path is needed later.");

//=============================================================================
// METHODS
//=============================================================================
    //--------------------------------------------------------------------------
    // CONSTRUCTION
    //--------------------------------------------------------------------------
public:
    ScaleTool();
    ScaleTool(const std::string& aFileName) SWIG_DECLARE_EXCEPTION;
    Model* createModel() const;
    /* Query the subject for different parameters */
    const GenericModelMaker& getGenericModelMaker() const {
        return get_generic_model_maker();
    }

    const ModelScaler& getModelScaler() const { return get_model_scaler(); }

    const MarkerPlacer& getMarkerPlacer() const { return get_marker_placer(); }

    /** Run the scale tool. This first runs the ModelScaler, then runs the
     * MarkerPlacer. This is the method called by the command line `scale`
     * executable. 
     * @returns whether or not the scale procedure was successful. */
    bool run() const;

    bool isDefaultGenericModelMaker() const {
        return getProperty_generic_model_maker().getValueIsDefault();
    }
    bool isDefaultModelScaler() const {
        return getProperty_model_scaler().getValueIsDefault();
    }
    bool isDefaultMarkerPlacer() const {
        return getProperty_marker_placer().getValueIsDefault();
    }

    /* Register types to be used when reading a ScaleTool object from xml file. */
    static void registerTypes();

    /** Accessor methods to obtain model attributes */
    double getSubjectMass() const { return get_mass(); }
    double getSubjectAge() const { return get_age(); }
    double getSubjectHeight() const { return get_height(); }
    void setSubjectMass(double mass) { set_mass(mass); }
    void setSubjectAge(double age) { set_age(age); }
    void setSubjectHeight(double height) { set_height(height); }
    /**
     * Accessor methods to set and get path to Subject. This is needed
     * since all file names referred to in the subject file are relative
     * to the subject file.
     */
    const std::string& getPathToSubject() const
    {
        return get_path_to_subject();
    }
    void setPathToSubject(const std::string& aPath)
    {
        set_path_to_subject(aPath);
    }
    //std::string getParentDirectory(const std::string& fileName);

    void setPrintResultFiles(bool aToWrite);

protected:

private:
    void constructProperties();

    //=============================================================================
};  // END of class ScaleTool
//=============================================================================
//=============================================================================

} // end of namespace OpenSim

#endif // OPENSIM_SCALE_TOOL_H_
