/*******************************************************************************

   COLOR.H

   Author: Peter Loan

   Date: 25-JUN-91

   Copyright (c) 1992-4 MusculoGraphics, Inc.
   All rights reserved.
   Portions of this source code are copyrighted by MusculoGraphics, Inc.

*******************************************************************************/

#define BLACK 0
#define RED 1
#define GREEN 2
#define YELLOW 3
#define BLUE 4
#define MAGENTA 5
#define CYAN 6
#define WHITE 7
#define DESKTOP_BACKGROUND 8
#define DESKTOP_BORDER 9
#define DESKTOP_TEXT 10
#define TOOL_TITLE_AREA_BACKGROUND 11
#define TOOL_TITLE_AREA_BORDER 12
#define TOOL_TITLE_AREA_TEXT 13
#define FORM_ITEM_BACKGROUND 14
#define FORM_ITEM_BORDER 15
#define FORM_ITEM_TEXT 16
#define FORM_ITEM_SELECTED_BACKGROUND 17
#define FORM_ITEM_SELECTED_BORDER 18
#define FORM_ITEM_SELECTED_TEXT 19
#define FORM_TITLE_BOX_BACKGROUND 20
#define FORM_TITLE_BOX_BORDER 21
#define FORM_TITLE_BOX_TEXT 22
#define MENU_ITEM_BACKGROUND 23
#define MENU_ITEM_BORDER 24
#define MENU_ITEM_TEXT 25
#define MENU_ITEM_SELECTED_BACKGROUND 26
#define MENU_ITEM_SELECTED_BORDER 27
#define MENU_ITEM_SELECTED_TEXT 28
#define MENU_TITLE_BOX_BACKGROUND 29
#define MENU_TITLE_BOX_BORDER 30
#define MENU_TITLE_BOX_TEXT 31
#define HELP_WINDOW_BACKGROUND 32
#define HELP_WINDOW_BORDER 33
#define HELP_WINDOW_TEXT 34
#define CONFIRM_WINDOW_BACKGROUND 35
#define CONFIRM_WINDOW_BORDER 36
#define CONFIRM_WINDOW_TEXT 37
#define TOOL_WINDOW_BACKGROUND 38
#define TOOL_WINDOW_BORDER 39
#define TOOL_WINDOW_TEXT 40
#define MISC_TEXTPORT 41
#define MISC_PLOT_BACKGROUND 42
#define MISC_PLOT_POINT 43
#define MISC_PLOT_LABELS 44
#define MISC_CURVE_NAME 45
#define MISC_CURVE_NAME_SELECTED 46
#define MISC_CURVE_BACKGROUND_SELECTED 47
#define MISC_CONFIRM_BORDER1 48
#define MISC_CONFIRM_BORDER2 49
#define MISC_CONFIRM_BORDER3 50
#define MISC_MUSCLE_POINT 51
#define MISC_MUSCLE_POINT_SELECTED 52
#define MISC_MUSCLE_LINE20 53
#define MISC_MUSCLE_LINE19 54
#define MISC_MUSCLE_LINE18 55
#define MISC_MUSCLE_LINE17 56
#define MISC_MUSCLE_LINE16 57
#define MISC_MUSCLE_LINE15 58
#define MISC_MUSCLE_LINE14 59
#define MISC_MUSCLE_LINE13 60
#define MISC_MUSCLE_LINE12 61
#define MISC_MUSCLE_LINE11 62
#define MISC_MUSCLE_LINE10 63
#define MISC_MUSCLE_LINE9 64
#define MISC_MUSCLE_LINE8 65
#define MISC_MUSCLE_LINE7 66
#define MISC_MUSCLE_LINE6 67
#define MISC_MUSCLE_LINE5 68
#define MISC_MUSCLE_LINE4 69
#define MISC_MUSCLE_LINE3 70
#define MISC_MUSCLE_LINE2 71
#define MISC_MUSCLE_LINE1 72
#define MISC_MUSCLE_LINE0 73
#define MISC_WIREFRAME_BONES 74
#define MISC_MODEL_WINDOW_BACKGROUND 75
#define MISC_HELP_TEXT_BOLD 76
#define MISC_GUI_SIDE1 77
#define MISC_GUI_SIDE2 78
#define MISC_GUI_SIDE3 79
#define MISC_GUI_SIDE4 80
#define MISC_TOGGLE_BUTTON_ON 81
#define MISC_TOGGLE_BUTTON_OFF 82
#define MISC_GUI_BORDER 83
#define MISC_BONE_POLYGON 84
#define MISC_BONE_POLYGON_VERTEX_LABELS 85
#define MISC_SLIDER_BACKGROUND 86
#define MISC_SLIDER_THUMB 87
#define MISC_SLIDER_THUMB_PRESSED 88
#define MISC_FORM_TEXT_HIGHLIGHT 89
#define MISC_FORM_CURSOR 90
#define MISC_PLOT_CURVE1 91
#define MISC_PLOT_CURVE2 92
#define MISC_PLOT_CURVE3 93
#define MISC_PLOT_CURVE4 94
#define MISC_PLOT_CURVE5 95
#define MISC_PLOT_CURVE6 96
#define MISC_PLOT_CURVE7 97
#define MISC_PLOT_CURVE8 98
#define MISC_PLOT_CURVE9 99
#define MISC_PLOT_CURVE10 100
#define MISC_PLOT_CURVE11 101
#define MISC_PLOT_CURVE12 102
#define MISC_PLOT_CURVE13 103
#define MISC_PLOT_CURVE14 104
#define MISC_PLOT_CURVE15 105
#define MISC_PLOT_CURVE16 106
#define MISC_PLOT_CURVE17 107
#define MISC_PLOT_CURVE18 108
#define MISC_PLOT_CURVE19 109
#define MISC_PLOT_CURVE20 110
#define MISC_SEGMENT_AXES 111
#define MISC_ROTATION_AXES 112
#define MISC_CROSSHAIRS 113
#define MISC_MOTION_EVENTS 114
#define FORM_ITEM_TEXT_ALT 115

