function out = testCompareSetupFiles2()

% Compare files from these two directories.
dir1 = 'D:\programfiles\FCA\SU\Testing\delaware2_1.5_ss_auto_sdfast_cfsqp\';
dir2 = 'D:\programfiles\FCA\SU\Testing\delaware2_1.5_ss_auto_sdfast_ipopt\';

% Create list of filenames.
filenames = { ...
    'de2_ss_walk1_CMC_Actuators.xml' ...
    'de2_ss_walk1_CMC_ControlConstraints.xml' ...
    'de2_ss_walk1_CMC_ControlConstraints_Constrained.xml' ...
    'de2_ss_walk1_CMC_Tasks.xml' ...
    'de2_ss_walk1_IK_Tasks.xml' ...
    'de2_ss_walk1_RRA_Actuators.xml' ...
    'de2_ss_walk1_RRA_ControlConstraints.xml' ...
    'de2_ss_walk1_RRA_Tasks.xml' ...
    'de2_ss_walk1_Setup_CMC.xml' ...
    'de2_ss_walk1_Setup_Constrained_CMC.xml' ...
    'de2_ss_walk1_Setup_Forward.xml' ...
    'de2_ss_walk1_Setup_ID_CMC.xml' ...
    'de2_ss_walk1_Setup_ID_IK.xml' ...
    'de2_ss_walk1_Setup_ID_RRA.xml' ...
    'de2_ss_walk1_Setup_IK.xml' ...
    'de2_ss_walk1_Setup_MuscleAnalysis.xml' ...
    'de2_ss_walk1_Setup_Perturb.xml' ...
    'de2_ss_walk1_Setup_RRA.xml' ...
    'delaware2_Scale_MarkerSet.xml' ...
    'delaware2_Scale_MeasurementSet.xml' ...
    'delaware2_Scale_ScaleSet.xml' ...
    'delaware2_Scale_Tasks.xml' ...
    'delaware2_Setup_Scale.xml' };

% Compare all non-RRA setup files.
out = '';
for i = 1 : length( filenames )
    file1 = fullfile( dir1, filenames{i} );
    file2 = fullfile( dir2, filenames{i} );
    out = [ out sprintf( '\n' ) compareSetupFiles( file1, file2 ) ]; %#ok<AGROW>
end
