name: Build Python wheels

on:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build_windows_wheels:

    runs-on: windows-2022

    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    outputs:
      version: ${{ steps.configure.outputs.version }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Python packages
      id: setup
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.python-version }}'

    - name: Install numpy
      # Need numpy to use SWIG numpy typemaps.
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install numpy==2.4.2 wheel build

    - name: Install SWIG
      run: |
        choco install swig --version 4.4.1 --yes --limit-output --allow-downgrade
        swig -swiglib

    - name: Build dependencies
      run: |
        chdir $env:GITHUB_WORKSPACE\\dependencies
        cmake -G "Visual Studio 17 2022" . --preset wheels-msvc-windows-release -LAH
        cmake --build --preset wheels-msvc-windows-release -j 4

    - name: Configure opensim-core
      id: configure
      run: |
        cmake -G "Visual Studio 17 2022" . --preset wheels-msvc-windows-release -LAH

        $env:match = cmake -N -L build/wheels-msvc-windows-release | Select-String -Pattern OPENSIM_QUALIFIED_VERSION
        $version = $env:match.split('=')[1]
        echo "version=$version" >> $env:GITHUB_OUTPUT
        echo "CMAKE_INSTALL_PREFIX=$env:GITHUB_WORKSPACE\build\wheels-msvc-windows-release\install" >> $env:GITHUB_OUTPUT
        echo "OPENSIM_DEPENDENCIES_DIR=$env:GITHUB_WORKSPACE\build\dependencies\wheels-msvc-windows-release\install" >> $env:GITHUB_OUTPUT

    - name: Build opensim-core
      run: |
        cmake --build --preset wheels-msvc-windows-release -j 4
        cmake --build --preset wheels-msvc-windows-release --target install

    - name: Build wheel
      run: |
        cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python
        pip wheel . --wheel-dir dist

    - name: Capture wheel path
      id: wheel
      shell: pwsh
      run: |
         cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python/dist
         $file = Get-ChildItem opensim*.whl | Select-Object -First 1
         echo "path=$($file.Name)" >> $env:GITHUB_OUTPUT

    - name: Upload windows wheel
      uses: actions/upload-artifact@v4
      with:
         name: wheels-${{ matrix.python-version }}-windows
         path: ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python/dist/opensim*.whl
         overwrite: true

    - name: Test Python bindings
      run: |
        cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python
        pip install dist/${{ steps.wheel.outputs.path }}
        # python3 -m unittest discover --start-directory opensim/tests --verbose

  build_osx_wheels:
    runs-on: macos-15
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']

    outputs:
      version: ${{ steps.configure.outputs.version }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Python packages
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.python-version }}'

    - name: Install Homebrew packages
      run: |
        brew install pkgconfig autoconf libtool automake wget pcre llvm bison
        brew reinstall gcc
        pip3 install numpy==2.4.2
        pip3 install wheel
        pip3 install build

    - name: Install SWIG
      run: |
        mkdir ~/swig-source && cd ~/swig-source
        wget https://github.com/swig/swig/archive/refs/tags/v4.4.1.tar.gz
        tar xzf v4.4.1.tar.gz && cd swig-4.4.1
        sh autogen.sh && BISON="$(brew --prefix bison)/bin/bison" ./configure --prefix=$HOME/swig --disable-ccache
        make && make -j4 install

    - name: Build dependencies
      run: |
        cd $GITHUB_WORKSPACE/dependencies
        cmake . --preset wheels-make-macos-release -LAH
        cmake --build --preset wheels-make-macos-release -j 4

    - name: Configure opensim-core
      id: configure
      run: |
        cmake -S $GITHUB_WORKSPACE --preset wheels-make-macos-release -LAH \
            -DSWIG_EXECUTABLE=$HOME/swig/bin/swig

        VERSION=`cmake -N -L $GITHUB_WORKSPACE/build/wheels-make-macos-release | grep OPENSIM_QUALIFIED_VERSION | cut -d "=" -f2`
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "CMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/build/wheels-make-macos-release/install" >> $GITHUB_OUTPUT
        echo "OPENSIM_DEPENDENCIES_DIR=$GITHUB_WORKSPACE/build/dependencies/wheels-make-macos-release/install" >> $GITHUB_OUTPUT

    - name: Build opensim-core
      run: |
        cmake --build --preset wheels-make-macos-release -j 4
        cmake --build --preset wheels-make-macos-release --target install

    - name: Build wheel
      run: |
        cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python
        python3 -m build --wheel

    - name: Capture wheel path
      id: wheel
      run: |
         cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python/dist
         echo "path=$(ls -1 opensim*.whl | head -n1)" >> $GITHUB_OUTPUT

    - name: Upload osx wheel
      uses: actions/upload-artifact@v4
      with:
         name: wheels-${{ matrix.python-version }}-osx
         path: ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python/dist/${{ steps.wheel.outputs.path }}
         overwrite: true

    - name: Test Python bindings
      run: |
        cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python
        pip3 install ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python/dist/${{ steps.wheel.outputs.path }}
        python3 -m unittest discover --start-directory opensim/tests --verbose

  build_linux_wheels:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux_2_28_x86_64

    strategy:
      matrix:
        python: ["cp311", "cp312", "cp313"]

    steps:
    - uses: actions/checkout@v4

    - name: Set Python
      run: echo "PY=/opt/python/${{ matrix.python }}-${{ matrix.python }}/bin/python" >> $GITHUB_ENV

    - name: Install Numpy
      run: |
        $PY -m pip install numpy==2.4.2
        $PY -m pip install build
        $PY -m pip install wheel
        $PY -m pip install auditwheel

    - name: Install packages
      run: |
        yum -y update
        yum -y install \
        gcc \
        gcc-c++ \
        make \
        libtool \
        autoconf \
        automake \
        pkgconfig \
        pcre2-devel \
        gcc-gfortran \
        openblas-devel \
        lapack-devel \
        freeglut-devel \
        libXi-devel \
        libXmu-devel \
        wget \
        tar \
        gzip \
        patchelf

    - name: Mark workspace as safe for git (manylinux container)
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git config --global --add safe.directory /__w/opensim-core/opensim-core

    - name: Build dependencies
      run: |
        cd $GITHUB_WORKSPACE/dependencies
        cmake . --preset wheels-make-linux-release -LAH
        cmake --build --preset wheels-make-linux-release -j 4

    - name: Configure opensim-core
      id: configure
      run: |
        cmake -S $GITHUB_WORKSPACE --preset wheels-make-linux-release -LAH \
            -DPython3_EXECUTABLE=$PY

        VERSION=`cmake -N -L $GITHUB_WORKSPACE/build/wheels-make-linux-release | grep OPENSIM_QUALIFIED_VERSION | cut -d "=" -f2`
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "CMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/build/wheels-make-linux-release/install" >> $GITHUB_OUTPUT
        echo "OPENSIM_DEPENDENCIES_DIR=$GITHUB_WORKSPACE/build/dependencies/wheels-make-linux-release/install" >> $GITHUB_OUTPUT

    - name: Build opensim-core
      run: |
        cmake --build --preset wheels-make-linux-release -j 4
        cmake --build --preset wheels-make-linux-release --target install

    - name: Test Python bindings
      run: |
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ steps.configure.outputs.OPENSIM_DEPENDENCIES_DIR }}/simbody/lib
        cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python
        $PY -m unittest discover --start-directory opensim/tests --verbose

    - name: Build wheel
      run: |
        cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python
        $PY -m build --wheel .

    - name: Twine and audit check
      run: |
        cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python
        $PY -m pip install --upgrade twine
        $PY -m twine check dist/*
        for whl in dist/*.whl; do
            echo "=== $whl ==="
            $PY -m auditwheel show "$whl"
          done

    - name: Repair wheels
      run: |
          cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python
          mkdir -p dist/repaired
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${{ steps.configure.outputs.OPENSIM_DEPENDENCIES_DIR }}/simbody/lib
          for whl in dist/*.whl; do
            echo "Repairing $whl"
            auditwheel repair "$whl" -w dist/repaired/
          done

    - name: Capture wheel path
      id: wheel
      run: |
         cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python/dist/repaired
         echo "path=$(ls -1 opensim*.whl | head -n1)" >> $GITHUB_OUTPUT

    - name: Upload linux wheel
      uses: actions/upload-artifact@v4
      with:
         name: wheels-${{ matrix.python }}-linux
         path: ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python/dist/repaired/opensim*.whl
         overwrite: true

    - name: Test Python bindings
      run: |
        cd ${{ steps.configure.outputs.CMAKE_INSTALL_PREFIX }}/sdk/Python
        $PY -m pip install dist/repaired/${{ steps.wheel.outputs.path }}
        $PY -m unittest discover --start-directory opensim/tests --verbose
